version: '3.8'

services:
  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - 443:443
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - ws:/var/www/html
  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    ports:
      - 9000:9000
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - ws:/var/www/html
    env_file:
      - ./.env
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql
    env_file:
      - ./.env

networks:
  inception:

volumes:
  ws:
  db: