version: '3.8'

services:
  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - 443:443
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - ws:/var/www/html
  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    ports:
      - 9000:9000
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    volumes:
      - ws:/var/www/html
    env_file:
      - ./.env
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql
    env_file:
      - ./.env
  redis:
    image: redis
    build: ./requirements/redis
    container_name: redis
    restart: always
    ports:
      - 6378:6379
    networks:
      - inception
    env_file:
      - ./.env
  adminer:
    image: adminer
    build: ./requirements/adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - inception
    depends_on:
      - mariadb
  ftp:
    image: ftp
    build: ./requirements/ftp
    container_name: ftp
    restart: always
    networks:
      - inception
    ports:
      - 21:21
      - 40000-40100:40000-40100
    volumes:
      - ws:/var/www/html

networks:
  inception:
  #bridge type is the default

volumes:
  ws:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /home/laundryday/data/ws
  db:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /home/laundryday/data/db